# Site settings
title: DropOffice
email: admin@dropofficespace.com
description: > # this means to ignore newlines until "baseurl:"
  Office space and desk space desigined around nomadic remote office workers.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://dropofficespace.com" # the base hostname & protocol for your site
twitter_username: dropoffice
github_username:  dropoffice
phone: +1 (503) 758-0
address: ""

# Build settings
markdown: kramdown


paginate: 3
paginate_path: "blog/page:num"